language: python
python:
- 3.5
env:
  global:
    secure: nmZmWp4vOxThqzWDMAUoBOkFw8jumD7i6U2Jxw8Dyk+DMPUXCG+BLiEfL+90NwbddDjyZpA0hytNxYDUU4U0O39ZS2apsMbFiFz07fUAUHnJ78C5cih6A7pqchVmtazaGPF3GGXAjlO6JLhNTFtEod7/019NN6LyWHWXtLhpgNq3q786TS407j+luP74v93SRLOMG9IMdFptuoyRYICVK3eTDT/P1RHi77x0UPIG2aQhsLxDecvpGGFzD6ay7vZJO5K9Powk2epCTjC8uB8G/ZKihOwFppJsGm9zLydhmvHdLBst5Tj+DVNmC1vPyLUkeGVygPYb6kSWEFmqKsIzGlLXgvFBygBnTlchbQXgtHq1niCNjgavOgwZTv7KbqSsnRO9T1ORsscZ344pnyXKthAwtV7qE7EoO7SScy0O7A5d/OCScLjuWYbbXV8JLtYLSfyl2BVukg8p0hs6yUMrxxjnxfyqjNcNZJ/ya5KlUtva/rRbfXrldZweiWLBEw+0IlKD10iXyPYPRy81Zb2KmahM/2xm6uXCK8ZgpaYLrm1eMSE70/9lb1Z0DxfsKE/RMcPICD+jAypR7I3I4V8MROvEsv3TPyuFMgDAWaDQOW1nz69PLa8H2nJxwTAHkQmtVv1Gmj45oXKO1ys865BNGizcALIBRUOpV2z/ikrmeiE=
